//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArticleTb()
        {
            this.CommentTb = new HashSet<CommentTb>();
        }
    
        public int articleId { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public int likeCount { get; set; }
        public int viewCount { get; set; }
        public System.DateTime publishTime { get; set; }
        public int authorId { get; set; }
        public bool isDel { get; set; }
        public string colm1 { get; set; }
        public string colm2 { get; set; }
    
        public virtual RoleTb RoleTb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentTb> CommentTb { get; set; }
    }
}
